apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-sqs-demo
  namespace: opensearch-sqs-demo
  labels:
    app: opensearch-sqs-demo
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-sqs-demo
  template:
    metadata:
      labels:
        app: opensearch-sqs-demo
        version: v1
    spec:
      containers:
      - name: opensearch-sqs-demo
        image: opensearch-sqs-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "local"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_LOCALSTACK_ENDPOINT
          value: "http://host.docker.internal:4566"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-sqs-demo-service
  namespace: opensearch-sqs-demo
  labels:
    app: opensearch-sqs-demo
spec:
  selector:
    app: opensearch-sqs-demo
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 